{smcl}
{* version 0.2.0 14mar2025  Hans Gerhardt and Anneke Kappes}{...}
{hi:labels_kldb92_3d()} {hline 2} KldB-1992 labels (3 digits)

{title:Description}

{pstd}
    {helpb kldbrecode} table providing labels for 3-digit KldB-1992 codes.

{title:Source}

{pstd}
    The German labels from file {bf:{browse "https://www.destatis.de/DE/Methoden/Klassifikationen/Berufe/klassifikationen-kldb-1992-xls.xlsx":Klassifizierung der Berufe 1992 (KldB 92)}}
    provided by Statistisches Bundesamt at {browse "https://www.destatis.de/DE/Methoden/Klassifikationen/Berufe/klassifikation-kldb-1992-4st.html"}
    were translated automatically using ChatGPT-4o by by OpenAI. 
    We have corrected misleading translations that occur systematically, but have not reviewed the full list of labels. 
    For example, 'Fachkräfte' has been translated as 'professionals', implying skill level 4. 
    In fact, the German term refers to skill level 2 - skilled workers.
    {p_end}

{hline}
{asis}
011 "Farmers, Plant Protectors"
012 "Vintners"
013 "Agricultural Laborers"
014 "Helping Family Members in Agriculture"
023 "Animal, Horse, Fish Farmers"
024 "Animal Caretakers and Related Occupations, n.e.c."
031 "Administrators in Agriculture and Animal Husbandry"
032 "Agricultural, Animal Husbandry Advisors"
051 "Gardeners, Garden Workers"
052 "Horticultural Engineers, Technicians"
053 "Florists"
061 "Forestry Managers, Foresters"
062 "Forest Workers"
070 "Miners n.e.c."
071 "Miners (Mining Technology)"
072 "Miners (Mechanical, Electrical Engineering)"
080 "Mineral Extractors, Processors"
101 "Stone, Gemstone Processors"
112 "Brick, Concrete (Stone) Manufacturers"
121 "Ceramicists (Coarse, Fine Ceramics)"
131 "Glass Manufacturers"
135 "Glass Processors, Refiner"
141 "Chemical Plant Operators"
142 "Chemical Laboratory Workers"
145 "Rubber Manufacturers, Rubber Processors"
150 "Plastic Processors"
152 "Plastic Molders"
153 "Plastic Workers, Plastic Product Makers"
161 "Paper Makers"
162 "Packaging Mechanics"
164 "Other Paper Processors"
171 "Typesetters"
172 "Printing Plate Makers"
173 "Printing Plate Manufacturers"
174 "Printers (Relief, Planographic, Intaglio)"
175 "Special Printers, Screen Printers"
178 "Bookbinders"
179 "Printing, Print Finishing Assistants"
181 "Wood Processing Mechanics"
185 "Occupations in woodworking and the manufacture of wood"
191 "Process Mechanics (Metal Production)"
194 "Process Mechanics (Metal Forming)"
201 "Foundry Mechanics and other caster occupations"
211 "Sheet Metal Pressers, Sheet Metal Drawers"
212 "Wire Formers, Wire Processors"
213 "Other Metal Formers"
220 "Cutting Machine Operators"
221 "Turners"
222 "Millers"
224 "Drillers, Boring Mill Operators"
225 "Metal Grinders"
229 "Other Occupations in cutting metal forming processes"
231 "Metal Polishers"
233 "Metal Finishers"
234 "Galvanizers, Metal Colorists"
235 "Enamelers, Hot-dip Galvanizers"
241 "Welders, Flame Cutters"
245 "Solders, Riveters"
250 "Plant, Construction Mechanics"
252 "Plant Mechanics (Apparatus Engineering)"
254 "Construction Mechanics (Equipment Engineering) and Associated Metalworkers"
255 "Construction Mechanics (Metal and Shipbuilding Technology)"
256 "Metalworkers (Metal Design)"
259 "Other Metal Construction"
261 "Plumbers"
264 "Plant Mechanics (Supply Technology)"
265 "Construction Mechanics (Fine Sheet Metal Construction)"
266 "Refrigeration Plant Builders, Refrigeration Plant Installers"
267 "Gas, Water Installers"
268 "Central Heating, Ventilation Builders"
269 "Installation and Assembly Occupations, n.e.c."
270 "Industrial Mechanics n.e.s.,"
273 "Industrial Mechanics (Machine and System Technology), Machine Mechanics"
274 "Industrial Mechanics (Operational Technology), Maintenance, Repair Locksmiths"
276 "Industrial Mechanics (Production Technology)"
278 "Part Fitters, Device, Machine Assemblers"
281 "Motor Vehicle and Bicycle Mechanics"
282 "Agricultural Machinery Mechanics"
283 "Aircraft, Jet Engine Mechanics"
287 "Body, Vehicle Builders"
290 "Tool Mechanics, Tool Makers n.e.s."
292 "Tool Mechanics (Stamping and Forming Technology), Tool Makers (Stamping Tool and Fixture Construction)"
293 "Tool Mechanics (Mold Technology), Tool Makers (Mold Making)"
294 "Engravers and Related Occupations"
295 "Tool Mechanics (Instrument Technology),"
300 "Industrial Mechanics (Device, Machine Assemblers)"
302 "Precious Metal Smiths"
303 "Dental Technicians"
304 "Opticians"
305 "Musical Instrument Makers"
307 "Orthopedic Mechanics, Bandagists"
308 "Watchmakers"
309 "Other Precision Mechanics and Related Occupations"
310 "Electricians n.e.s."
311 "Power Electronics Technicians (Plant, Operational Technology)"
312 "Telecommunication Systems, Telecommunication Electronics Technicians"
313 "Electrical Machine Builders, Electrical Machine Assemblers"
315 "Radio and Television Technicians (Broadcast Mechanics) and Related Occupations"
316 "Electromechanics Technicians, Industrial Electronics Technicians"
317 "Communication, Office Information Electronics Technicians"
318 "Automotive Electricians"
321 "Assemblers of Electronic Devices or Parts"
322 "Other Assemblers"
323 "Metalworkers n.e.s."
331 "Spinners, Spinner Preparers"
332 "Reelers, Twisters, Rope Makers"
341 "Weavers"
344 "Knitted Goods Makers"
349 "Other Occupations"
351 "Outerwear Tailors"
352 "Outerwear Sewers"
353 "Laundry Tailors, Laundry Sewers"
354 "Clothing Accessories Makers"
358 "Textile Sewers, n.e.c."
359 "Other Textile Processors"
361 "Textile Finishers"
371 "Tanners, Catgut Makers"
372 "Shoemakers (Craft)"
373 "Shoe Manufacturers (Industry)"
374 "Saddlers"
376 "Leather Garment Manufacturers, Other Leather Processors"
378 "Fur Processors"
391 "Bakers"
392 "Confectioners"
393 "Sugar, Sweets, Ice Cream Makers"
401 "Butchers"
411 "Cooks"
421 "Brewers and Maltsters"
423 "Other Beverage Manufacturers, Tasters"
424 "Tobacco Product Makers"
431 "Dairy Specialists"
435 "Other Occupations"
440 "Building Construction Occupations n.e.c."
441 "Bricklayers, Furnace and Chimney Builders"
442 "Concrete and Reinforced Concrete Builders"
443 "Scaffolders"
460 "Occupations in Civil Engineering n.e.c.,"
461 "Road Builders"
463 "Track Builders"
465 "Cultural, Water Builders"
466 "Other Civil Engineering Occupations"
471 "Earthmoving Workers"
472 "Other Construction Work Assistants, n.e.c."
480 "Finishing Occupations n.e.c."
481 "Plasterers"
482 "Insulators, Sealers"
483 "Tile, Slab, Mosaic Layers"
484 "Tile Stove and Air Heating Builders"
485 "Glaziers"
486 "Screed, Terrazzo Layers"
487 "Carpenters"
488 "Roofers"
491 "Interior Decorators, Parquet Layers"
492 "Upholsterers"
501 "Carpenters"
502 "Model Making Occupations"
505 "Wood Mechanics"
506 "Wood, Plastic Construction Builders"
510 "Painters and Varnishers n.e.s."
511 "Painters and Varnishers (Contruction)"
512 "Product Painters, Product Varnishers"
514 "Glass, Ceramic, Porcelain Painters"
521 "Product, Manufacturing Inspectors, n.e.c."
522 "Product Preparers, Shipping Preparers"
523 "Product Sorters, n.e.c."
531 "Helpers without Specific Occupation Description"
540 "Machinery Operators, Machinists"
541 "Energy Machinists"
544 "Crane Operators"
545 "Earthmoving Machine Operators"
546 "Construction Machine Operators, n.e.c."
549 "Other Machine, Plant Operators and Helpers, n.e.c."
550 "Machine Setters, n.e.c."
600 "Engineers, n.e.c."
601 "Engineers for Machines, Apparatus, and Vehicle Construction"
602 "Electrical Engineers"
603 "Civil Engineers"
604 "Surveying and Cartography Engineers"
605 "Mining, Metallurgy, Foundry Engineers"
606 "Other Manufacturing Engineers"
607 "Economic, Industrial Engineers"
608 "Other Engineers"
609 "Architects, Urban Planners, n.e.c."
611 "Chemists, Chemical, Process Engineers"
612 "Physicists, Physics Engineers, Mathematicians"
620 "Technicians, n.e.c."
621 "Technicians for Machines, Apparatus, and Vehicle Construction"
622 "Electrical Engineering Technicians"
623 "Civil Engineering Technicians"
624 "Surveying Technicians"
625 "Mining, Metallurgy, Foundry Technicians"
626 "Chemical, Physical Technicians"
627 "Other Production Technicians"
628 "Technicians in Business Administration and Industrial Engineering"
629 "Other Technicians"
631 "Biological Technical Specialists"
632 "Physical Technical Specialists"
633 "Chemical Laboratory Technicians"
634 "Photo, Film, Video Laboratory Assistants"
641 "Technical Draftspersons"
642 "Construction Draftspersons, Cartographers and related professions"
651 "Industrial, Plant Foremen"
652 "Trainers for Technical Vocational Professions, Training Foremen"
660 "Salespeople, not otherwise specified"
661 "Food, Beverages Salespersons"
662 "Other Specialist Salespeople"
663 "Traveling Salespeople"
670 "Merchants, n.e.c."
671 "Wholesale and Foreign Trade Merchants"
672 "Retail Merchants without field specification, Itinerant Traders"
673 "Retail Merchants with field specification, n.e.c."
674 "Book, Music Merchants"
675 "Druggists, Health Food Merchants"
676 "Store Managers, Branch Managers"
677 "Purchasers, Purchase Managers"
678 "Sales, Distribution Clerks"
683 "Publishing Merchants"
685 "Assistant pharmacists"
686 "Petrol Station Attendants"
687 "Commercial Agents, Sales Representatives"
689 "Other Representatives"
691 "Banking Professionals"
692 "Building Society Professionals"
695 "Insurance Professionals (not statutory social insurance)"
701 "Transportation Merchants (Freight Transport)"
702 "Transportation Specialists (Passenger, Tourism)"
703 "Advertising Specialists"
704 "Commercial Brokers, Real Estate Agents"
705 "Agents, n.e.c."
706 "Cashiers and Payout Clerks, Ticket Sellers and Controllers"
711 "Rail Vehicle Drivers"
712 "Railway Operational Staff"
713 "Vehicel Operational Staffs"
714 "Professional Drivers, Coachmen"
715 "Haulage, Taxi Operators"
716 "Road Maintenance Workers"
721 "Captains (Coastal, Seafaring), Nautical and Technical Ship Officers"
723 "Ship Mechanics, Sailors, Ship Operations Managers"
724 "Occupations in Inland Navigation"
726 "Air Traffic Occupations"
731 "Postmasters"
732 "Service Specialists in Postal Service"
735 "Occupations in Radio and Telephony"
741 "Warehouse Managers, Storekeepers"
742 "Transport Equipment Operators"
743 "Stevedores, Furniture Movers"
744 "Warehouse, Transport Workers"
750 "Entrepreneurs, Managers, n.e.c."
751 "Business Division Managers, Executive Assistants, n.e.c."
753 "Financial Auditors, Tax Consultants and related professions"
754 "Specialists in Tax and Business Consulting, Tax Experts, n.e.c."
755 "Marketing, Sales Specialists"
756 "Organizers, Controllers and related professions, n.e.c."
757 "Management Consultants and related professions"
761 "Members of Parliament, Ministers, Elected Officials"
763 "Association Leaders, Functionaries"
764 "Administrative Civil Servants (Senior Service) n.e.c."
765 "Administrative Civil Servants (Upper Service) n.e.c."
771 "Finance, Accounting Specialists, Calculators"
772 "Accountants"
773 "Cash Specialists"
774 "Data Processing Specialists, IT Professionals"
775 "Software Developers"
776 "IT Organizers and related professions"
777 "IT Consulting and Sales Specialists"
778 "Data Center and IT User Service Specialists"
779 "Other Data Processing Specialists,"
780 "Office Specialists, Commercial Clerks n.e.c."
782 "Clerical Staff, Text Processing Specialists"
783 "Data Typists"
784 "Office Assistants"
785 "Industrial Clerks, Technical Clerks, Business Administrators (without diploma), n.e.c."
786 "Legal Assistants"
787 "Administrative Civil Servants (Middle Service) n.e.c."
788 "Office and Commercial Clerks n.e.c."
789 "Secretaries"
791 "Plant Security, Personal Protection Specialists, Detectives"
792 "Guards, Warden"
793 "Doormen"
794 "House, Commercial Servants"
795 "Swimming Supervisors, Lifeguards (Swimming Pool)"
796 "Janitors, Custodians"
801 "Soldiers, Border Guards, Police Officers"
802 "Professional Firefighters, Fire Protection Specialists"
803 "Security Inspectors"
804 "Chimney Sweeps"
805 "Health Protection Professions"
811 "Judges, Prosecutors"
812 "Judicial Officers (Senior Judicial Service)"
813 "Legal Representatives, Legal Advisors"
814 "Law Enforcement Officers, Prison Staff"
821 "Publishers"
822 "Interpreters, Translators"
823 "Librarians, Archivists"
831 "Musicians"
832 "Performing Artists"
833 "Fine Artists (Free Art)"
834 "Fine Artists (Applied Art)"
835 "Stage, Image, Sound Technicians and associated professions"
836 "Space, Visual Merchandisers"
837 "Photographers, Cameramen"
838 "Acrobats, Professional Athletes, Artistic Support Professions"
839 "Sign and Light Advertising Manufacturers"
841 "Medical Doctors"
842 "Dentists"
843 "Veterinarians"
844 "Pharmacists"
851 "Heilpraktiker/Heilpraktikerinnen (Non-medical Practitioners)"
852 "Massage Therapists, Medical Bath Attendants and Physiotherapists"
853 "Nurses, Midwives"
854 "Nursing Assistants"
855 "Dietitians, Nutrition Specialists"
856 "Receptionists in medical practice"
857 "Medical Technical Specialists"
858 "Pharmaceutical Technical Specialists"
859 "Therapeutic Professions, n.e.c."
861 "Social Work Professionals, Pedagogues"
862 "Special Needs Professionals, Pedagogues"
863 "Educators and Child Care Specialists"
864 "Elderly Care Workers"
865 "Family Caregivers"
866 "Special Needs Caregivers"
867 "Childcare Workers"
868 "Job, Career Consultants"
869 "Other Social Occupations"
870 "Teachers without specific indication"
871 "University Lectures and related professions"
872 "Upper Secondary School Teachers"
873 "Primary, Intermediate, Special School Teachers"
874 "Vocational School Teachers"
875 "Teachers for Music, Artistic Subjects, n.e.c."
876 "Sports Instructors"
878 "Driving, Traffic Instructors"
879 "Other Teachers"
880 "Scientists without specific indication"
881 "Economists, n.e.c."
882 "Humanities Scholars, n.e.c."
883 "Natural Scientists, n.e.c."
884 "Social Scientists, n.e.c."
885 "Educational Scientists, n.e.c."
886 "Psychologists"
887 "Statisticians, Market Researchers, and related professions"
891 "Clergy"
894 "Pastoral, Religious Assistants, Monastic Members without Specification"
901 "Hairdressers"
902 "Cosmeticians"
911 "Hoteliers, Innkeepers, n.e.c."
912 "Restaurant Specialists, Stewards"
914 "Hotel, Restaurant Merchants, n.e.c."
915 "Other Guest Services Occupations"
921 "Home Economists and Nutritional Professionals"
923 "Domestic Helpers"
931 "Textile Cleaners, Textile Caretakers"
934 "Building Cleaners, Room Cleaners"
935 "City Cleaners, Disposal Workers"
936 "Vehicle Cleaners, Vehicle Caretakers"
937 "Machine, Container Cleaners"
971 "Unpaid Family Members (not agriculture)"
981 "Apprentices with undetermined training profession"
982 "Interns, Trainees"
983 "Job Seekers"
991 "Skilled Workers without specific task"
992 "Home Workers without specific task"
993 "Foremen, Group Leaders without specific task"
994 "Conscientious Objectors without specific task"
995 "Self-employed without specific task"
996 "Consultation, Planning Specialists without specific task"
997 "Other Workers without specific task"
